alter system set nls_length_semantics='char' scope=both;
alter system set open_cursors = 1000 scope=both;
alter system set cursor_sharing=FORCE scope=both;
alter session set container = XEPDB1;
create tablespace maxdata datafile 'maxdata.dbf' size 1000M autoextend on;
create temporary tablespace maxtemp tempfile 'maxtemp.dbf' size 1000M autoextend on maxsize unlimited;
create user maximo identified by maximo default tablespace maxdata temporary tablespace maxtemp;
grant connect to maximo;
grant create job to maximo;
grant create trigger to maximo;
grant create session to maximo;
grant create sequence to maximo;
grant create synonym to maximo;
grant create table to maximo;
grant create view to maximo;
grant create procedure to maximo;
grant alter session to maximo;
grant execute on ctxsys.ctx_ddl to maximo;
alter user maximo quota unlimited on maxdata;
commit;

